defaults:
  app:
    publishMetaData: !env:bool PUBLISH_METADATA

  # Taskcluster credentials
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN

  monitoring:
    enable: !env:bool MONITORING_ENABLE
    level: !env LEVEL
    pretty: !env:bool PRETTY_LOGGING

  worker:
    provisionerId: "built-in"
    workerGroup: "built-in"

test:
  app:
    publishMetaData: false

  monitoring:
    enable: false
